name: Test

on: [push]
  branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Test
        run: make test
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: akhileshns/heroku-deploy@v3.2.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "braddle-music-rest"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true


